PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS schema_migrations (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE,
    applied_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS categories (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    slug TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS tools (
    id INTEGER PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    category_id INTEGER REFERENCES categories(id),
    subcategory TEXT,
    pricing_type TEXT,
    rating REAL,
    website TEXT,
    open_source INTEGER NOT NULL DEFAULT 0,
    offline INTEGER NOT NULL DEFAULT 0,
    ai_powered INTEGER NOT NULL DEFAULT 0,
    minimum_ram_gb REAL,
    system_level TEXT,
    editor_choice INTEGER NOT NULL DEFAULT 0,
    popularity_score INTEGER NOT NULL DEFAULT 0,
    date_added TEXT,
    payload_json TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS platforms (id INTEGER PRIMARY KEY AUTOINCREMENT, slug TEXT NOT NULL UNIQUE, name TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS tool_platforms (tool_id INTEGER NOT NULL REFERENCES tools(id) ON DELETE CASCADE, platform_id INTEGER NOT NULL REFERENCES platforms(id) ON DELETE CASCADE, PRIMARY KEY(tool_id, platform_id));
CREATE TABLE IF NOT EXISTS tags (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS tool_tags (tool_id INTEGER NOT NULL REFERENCES tools(id) ON DELETE CASCADE, tag_id INTEGER NOT NULL REFERENCES tags(id) ON DELETE CASCADE, PRIMARY KEY(tool_id, tag_id));
CREATE TABLE IF NOT EXISTS languages (id INTEGER PRIMARY KEY AUTOINCREMENT, code TEXT NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS tool_languages (tool_id INTEGER NOT NULL REFERENCES tools(id) ON DELETE CASCADE, language_id INTEGER NOT NULL REFERENCES languages(id) ON DELETE CASCADE, PRIMARY KEY(tool_id, language_id));
CREATE TABLE IF NOT EXISTS collections (id INTEGER PRIMARY KEY AUTOINCREMENT, slug TEXT NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS tool_collections (tool_id INTEGER NOT NULL REFERENCES tools(id) ON DELETE CASCADE, collection_id INTEGER NOT NULL REFERENCES collections(id) ON DELETE CASCADE, PRIMARY KEY(tool_id, collection_id));
CREATE TABLE IF NOT EXISTS tool_alternatives (tool_id INTEGER NOT NULL REFERENCES tools(id) ON DELETE CASCADE, alternative_tool_id INTEGER NOT NULL REFERENCES tools(id) ON DELETE CASCADE, PRIMARY KEY(tool_id, alternative_tool_id));
CREATE TABLE IF NOT EXISTS tool_change_history (id INTEGER PRIMARY KEY AUTOINCREMENT, tool_id INTEGER NOT NULL REFERENCES tools(id) ON DELETE CASCADE, event_date TEXT, event_type TEXT, summary TEXT, payload_json TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS tool_price_history (id INTEGER PRIMARY KEY AUTOINCREMENT, tool_id INTEGER NOT NULL REFERENCES tools(id) ON DELETE CASCADE, event_date TEXT, payload_json TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS articles (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    slug TEXT NOT NULL UNIQUE,
    title TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    content_type TEXT,
    category_id INTEGER REFERENCES categories(id),
    published_at TEXT,
    updated_at TEXT,
    author TEXT,
    payload_json TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS article_related_tools (article_id INTEGER NOT NULL REFERENCES articles(id) ON DELETE CASCADE, tool_id INTEGER NOT NULL REFERENCES tools(id) ON DELETE CASCADE, PRIMARY KEY(article_id, tool_id));
CREATE TABLE IF NOT EXISTS article_related_articles (article_id INTEGER NOT NULL REFERENCES articles(id) ON DELETE CASCADE, related_article_id INTEGER NOT NULL REFERENCES articles(id) ON DELETE CASCADE, PRIMARY KEY(article_id, related_article_id));
CREATE TABLE IF NOT EXISTS update_checklist_items (id INTEGER PRIMARY KEY AUTOINCREMENT, position INTEGER NOT NULL, payload_json TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_tools_slug ON tools(slug);
CREATE INDEX IF NOT EXISTS idx_tools_category ON tools(category_id);
CREATE INDEX IF NOT EXISTS idx_articles_slug ON articles(slug);
